DFE-Digital/care-leavers

- .github/workflows/validate-e2e.yaml
- .github/workflows/validate-sonarcloud.yml
- src/e2e/CareLeavers.E2ETests/package.json
- src/e2e/CareLeavers.E2ETests/playwright-ci.config.ts
- src/e2e/CareLeavers.E2ETests/playwright.config.ts
- src/e2e/CareLeavers.E2ETests/src/pages/HomePage.ts
- src/infrastructure/docker/docker-compose.yml
- Run app in docker compose (currently against the dev branch on contentful)
- Playwright CI settings to target docker compose URL (which is http)
- Simplified assertions to work with what is in contentful
> Get playwright working with docker compose

- src/contentful/CareLeavers.ContentfulMigration/CareLeavers.ContentfulMigration.csproj
- src/contentful/CareLeavers.ContentfulMigration/Migrations/0018-add-riddle-block.cjs
- src/web/CareLeavers.Web/AssetSrc/scss/application.scss
- src/web/tests/CareLeavers.Integration.Tests/Tests/SnapshotTests/Output/HomePageWithSupport.html
- src/web/tests/CareLeavers.Integration.Tests/Tests/SnapshotTests/Output/SimpleAsset.html
- src/web/tests/CareLeavers.Integration.Tests/Tests/SnapshotTests/Output/SimpleParagraph.html
- Updated SCSS to reference full GDS Design System
- Updated override to use font override variable
- Added riddle wrapper
> Riddle CSS Updates

- src/contentful/CareLeavers.ContentfulMigration/Program.cs
- Updated to ensure the migration tracker checks that the migrations were successfully applied
- Simplified some of the code slightly
> Ensure migrations ran successfully

- src/web/CareLeavers.Web/appsettings.json
Added contentful app to the allow frames URL list
> Allow Contentful App to Frame Site

- src/contentful/CareLeavers.ContentfulMigration/Migrations/0026-make-banner-title-not-unique.cjs
- src/contentful/CareLeavers.ContentfulMigration/Migrations/0027-allow-h2-in-footer.cjs
- src/contentful/CareLeavers.ContentfulMigration/Migrations/0028-add-feedback-link-to-configuration.cjs
- src/web/CareLeavers.Web/Models/Content/ContentfulConfigurationEntity.cs
- src/web/CareLeavers.Web/Program.cs
- src/web/CareLeavers.Web/Views/Shared/Grid/Card.cshtml
- src/web/CareLeavers.Web/Views/Shared/Grid/ExternalAgency.cshtml
- src/web/CareLeavers.Web/Views/Shared/_Header.cshtml
- src/web/tests/CareLeavers.Integration.Tests/Tests/SnapshotTests/Output/ComponentTest.html
- src/web/tests/CareLeavers.Integration.Tests/Tests/SnapshotTests/Output/HomePageWithSupport.html
- src/web/tests/CareLeavers.Integration.Tests/Tests/SnapshotTests/Output/SimpleAsset.html
- src/web/tests/CareLeavers.Integration.Tests/Tests/SnapshotTests/Output/SimpleParagraph.html
Fixed the following
- Live preview
- Image display in external links (for logos)
- Made banner title non-unique
- Updated cards to not use alt text and mark as presentation only
- Allow H2 in the footer
- Added feedback text and destination into configuration
> Various Fixes

- src/web/CareLeavers.Web/Views/Shared/Navigation.cshtml
Updated to make navigation highlight the parent page before the homepage, so guides etc will highlight the guides, support will highlight support etc
> Navigation Bar Fix

- src/web/CareLeavers.Web/TagHelpers/GDSContentfulContentsTagHelper.cs
Updates:
- Fix links in "contents" blocks to ensure correct link text
> Link Styling

- src/e2e/CareLeavers.E2ETests/src/helpers/urls-to-check.ts
- src/e2e/CareLeavers.E2ETests/src/tests/HomePage.spec.ts
- src/web/CareLeavers.Web/Contentful/ContentfulContentService.cs
- src/web/CareLeavers.Web/Contentful/IContentService.cs
- src/web/CareLeavers.Web/Controllers/ContentfulController.cs
- src/web/CareLeavers.Web/Views/Shared/Banner.cshtml
- src/web/tests/CareLeavers.Integration.Tests/TestSupport/FakeMessageHandler.cs
- src/web/tests/CareLeavers.Integration.Tests/Tests/ContentfulControllerTests.cs
- src/web/tests/CareLeavers.Integration.Tests/Tests/SnapshotTests/Input/HomePageWithSupport/banner_3e0VzPdXmMAFI278R8fTdJ.json
- src/web/tests/CareLeavers.Integration.Tests/Tests/SnapshotTests/Input/PageWithBanner/banner_GGBCsQbQMvRik6fogTyEv.json
- src/web/tests/CareLeavers.Integration.Tests/Tests/SnapshotTests/Output/HomePageWithSupport.html
- src/web/tests/CareLeavers.Integration.Tests/Tests/SnapshotTests/Output/PageWithBanner.html
- src/web/tests/CareLeavers.Integration.Tests/Tests/SnapshotTests/SnapshotTestCase.cs
- src/web/tests/CareLeavers.Integration.Tests/Tests/SnapshotTests/SnapshotTests.cs
- src/web/tests/CareLeavers.Integration.Tests/Tests/WebFixture.cs
Fixed the following bug:
- Banner not directing to the correct page
- Fixed by hydrating banners
Fixed end to end tests now URLs have changed
> Content and Test Fixes 

- src/infrastructure/terraform/frontdoor.tf
- src/web/CareLeavers.Web/Program.cs
Custom domain wasn't passing through in the host header correctly
> Enabling custom domain

- src/contentful/CareLeavers.ContentfulMigration/Migrations/0036-riddle-and-status-checker.cjs
- src/web/CareLeavers.Web/Contentful/ContentfulContentService.cs
- src/web/CareLeavers.Web/Contentful/IContentService.cs
- src/web/CareLeavers.Web/Controllers/StatusCheckerController.cs
- src/web/CareLeavers.Web/Views/Shared/StatusChecker.cshtml
- src/web/CareLeavers.Web/appsettings.json
There were some inconsistencies in the Contentful models and the model hydration had broken the status checker itself.
Now added back in
> Riddle and Status Checker

- src/e2e/CareLeavers.E2ETests/src/pages/CareTermsExplainedPage.ts
- src/e2e/CareLeavers.E2ETests/src/pages/LeavingCareGuidesPage.ts
- src/e2e/CareLeavers.E2ETests/src/pages/WhatHappensWhenYouLeaveCarePage.ts
- src/e2e/CareLeavers.E2ETests/src/tests/CareTermsExplained.spec.ts
- src/e2e/CareLeavers.E2ETests/src/tests/LeavingCareGuidesPage.spec.ts
- src/e2e/CareLeavers.E2ETests/src/tests/WhatHappensWhenYouLeaveCarePage.spec.ts
Test for Leaving care guides and its sub category pages
> Care 841 automate leaving care guides and subcategory pages

- src/web/CareLeavers.Web/Contentful/Webhooks/PublishAssetWebhook.cs
- src/web/CareLeavers.Web/Contentful/Webhooks/PublishContentfulWebhook.cs
- src/web/CareLeavers.Web/Program.cs
- Created webhook to handle when an image/video is updated to ensure all pages it exists on are also purged
- Tidied up webhook code
> Entry and Asset Webhooks

- src/infrastructure/terraform/frontdoor.tf
- src/infrastructure/terraform/variables.tf
Updated to make the managed rules only apply if azure front door is set to premium
> Correct Terraform for Premium vs Standard

- src/e2e/CareLeavers.E2ETests/playwright-ci.config.ts
- src/e2e/CareLeavers.E2ETests/playwright.config.ts
- src/e2e/CareLeavers.E2ETests/src/helpers/urls-to-check.ts
- src/e2e/CareLeavers.E2ETests/src/pages/AllSupportPage.ts
- src/e2e/CareLeavers.E2ETests/src/pages/EligibleChildPage.ts
- src/e2e/CareLeavers.E2ETests/src/pages/FormerRelevantPage.ts
- src/e2e/CareLeavers.E2ETests/src/pages/HelplinesPage.ts
- src/e2e/CareLeavers.E2ETests/src/pages/PersonQualifyingPage.ts
- src/e2e/CareLeavers.E2ETests/src/pages/RelevantChildPage.ts
- src/e2e/CareLeavers.E2ETests/src/pages/YourRightsPage.ts
- src/e2e/CareLeavers.E2ETests/src/tests/AllSupportPage.spec.ts
- src/e2e/CareLeavers.E2ETests/src/tests/BreadCrumbs.spec.ts
- src/e2e/CareLeavers.E2ETests/src/tests/Cookies.spec.ts
- src/e2e/CareLeavers.E2ETests/src/tests/HelplinesPage.spec.ts
- src/e2e/CareLeavers.E2ETests/src/tests/SharedLinks.spec.ts
-Tests For Helpline page
-Removed Duplicate Validation
-Reduced number of tests
-All support page
> Care 842 automate helplines page

- src/web/CareLeavers.Web/Views/Shared/Navigation.cshtml
- src/web/tests/CareLeavers.Integration.Tests/Tests/SnapshotTests/Output/HomePageWithSupport.html
- src/web/tests/CareLeavers.Integration.Tests/Tests/SnapshotTests/Output/PageWithBanner.html
- src/web/tests/CareLeavers.Integration.Tests/Tests/SnapshotTests/Output/SimpleAsset.html
Removed script block from navigation that upset the govuk frontend
> Fix End to End Tests on Mobile

- src/contentful/CareLeavers.ContentfulMigration/Migrations/0042-add-blocked-message-to-config.cjs
- src/infrastructure/terraform/frontdoor.tf
- src/web/CareLeavers.Web/Controllers/PagesController.cs
- src/web/CareLeavers.Web/Controllers/RobotsController.cs
- src/web/CareLeavers.Web/Controllers/SitemapController.cs
- src/web/CareLeavers.Web/Models/Content/ContentfulConfigurationEntity.cs
- src/web/CareLeavers.Web/Views/Pages/Error.cshtml
- src/web/CareLeavers.Web/Views/Pages/ServiceUnavailable.cshtml
Fixes https://dfedigital.atlassian.net/browse/CARE-905
> Geoblocking - Service Unavailable Message

- src/e2e/CareLeavers.E2ETests/src/pages/HomePage.ts
- src/web/CareLeavers.Web/AssetSrc/scss/application.scss
- src/web/CareLeavers.Web/Controllers/PagesController.cs
- src/web/CareLeavers.Web/Controllers/RobotsController.cs
- src/web/CareLeavers.Web/Controllers/TranslationController.cs
- src/web/CareLeavers.Web/Models/ViewModels/ConfigViewModel.cs
- src/web/CareLeavers.Web/Models/ViewModels/TranslationViewModel.cs
- src/web/CareLeavers.Web/Views/Contentful/Page.cshtml
- src/web/CareLeavers.Web/Views/Pages/ServiceUnavailable.cshtml
- src/web/CareLeavers.Web/Views/Shared/_BasicLayout.cshtml
- src/web/CareLeavers.Web/Views/Shared/_Footer.cshtml
- src/web/CareLeavers.Web/Views/Shared/_Header.cshtml
- src/web/CareLeavers.Web/Views/Translation/Index.cshtml
- src/web/tests/CareLeavers.Integration.Tests/Tests/SnapshotTests/Output/HomePageWithSupport.html
- src/web/tests/CareLeavers.Integration.Tests/Tests/SnapshotTests/Output/PageWithBanner.html
- src/web/tests/CareLeavers.Integration.Tests/Tests/SnapshotTests/Output/SimpleAsset.html
- Updated to disable translation, footer links, and navigation on the service unavailable page  [CARE-905](https://dfedigital.atlassian.net/browse/CARE-905)
- Updated phase banner [CARE-906](https://dfedigital.atlassian.net/browse/CARE-906)
- Updated translation to translate the current page
- Updated translation logo to also be clickable [CARE-919](https://dfedigital.atlassian.net/browse/CARE-919)
- Updated to pull through SEO title, if specified, correctly [CARE-898](https://dfedigital.atlassian.net/browse/CARE-898)
> Multiple Design/Layout Fixes

- src/web/CareLeavers.Web/AssetSrc/scss/application.scss
- src/web/CareLeavers.Web/AssetSrc/scss/metadata.scss
- src/web/CareLeavers.Web/Views/Shared/Grid/Card.cshtml
- src/web/tests/CareLeavers.Integration.Tests/Tests/SnapshotTests/Output/HomePageWithSupport.html
Reverts DFE-Digital/care-leavers#130
> Revert "Feat/print styling"

- src/infrastructure/docker/docker-compose.yml
- src/web/CareLeavers.Web/Dockerfile
Updated to remove extra bits from docker-compose.yml and Dockerfile
> Fix deployments

- src/contentful/CareLeavers.ContentfulMigration/Migrations/0051-printable-configuration.cjs
- src/infrastructure/terraform/frontdoor.tf
- src/web/CareLeavers.Web/Contentful/ContentfulContentService.cs
- src/web/CareLeavers.Web/Contentful/IContentService.cs
- src/web/CareLeavers.Web/Models/Content/ContentfulConfigurationEntity.cs
- src/web/CareLeavers.Web/Views/Shared/LastUpdated.cshtml
- src/web/CareLeavers.Web/Views/Shared/PrintThisPage.cshtml
- src/web/CareLeavers.Web/Views/Shared/Shareaholic.cshtml
- Add configuration for printable collection page
- Allow pages to determine if they are in a printable collection
- Show link to printable collection page if they are
> Printable Collection Updates

- src/infrastructure/terraform/frontdoor.tf
Adding new sections to the firewall for:
- Search engines
- Social Media
- Tools (eg: Slack etc)
- AI (eg: chatgpt, gemini)
> Firewall rules

- src/web/CareLeavers.Web/Contentful/ContentfulContentService.cs
- src/web/CareLeavers.Web/Contentful/Webhooks/PublishContentfulWebhook.cs
- src/web/CareLeavers.Web/Controllers/PrintController.cs
Updated to clear cache for printable collections and their PDFs whenever any pages update
> Printable Content Caching

- src/contentful/CareLeavers.ContentfulMigration/Migrations/0053-add-result-content-tag.cjs
- src/web/CareLeavers.Web/Controllers/PrintController.cs
- src/web/CareLeavers.Web/Views/Shared/_Header.cshtml
- src/web/CareLeavers.Web/Views/Translation/Index.cshtml
Fixes the following:
- PDF Generation was not correctly setting sandbox mode
- Language selection now passes hreflang
> Pass language selection and fix PDF generation

- src/web/CareLeavers.Web/Views/Contentful/Page.cshtml
- src/web/tests/CareLeavers.Integration.Tests/Tests/SnapshotTests/Output/PageWithBanner.html
Updated print js handler to only appear on pages with ShowPrintButton set to true
> Print Handler Fix

- src/infrastructure/terraform/frontdoor.tf
Fixing the following:
- Blocking The National Archive from indexing PDF and translated pages
- Blocking AI tools from indexing the translation page and PDF pages
> Front Door Fixes

- docs/architecture/Deployment-Architecture.md
- docs/architecture/Front-Door.md
- docs/architecture/adr/004-hybrid-caching.md
- docs/developers/Project-Setup.md
Updated technical documentation regarding:
- Hybrid Caching
- The deployment methods
- Local setup
- Front Door
> Updated Documentation

- src/contentful/CareLeavers.ContentfulMigration/Migrations/0055-add-button.cjs
- src/contentful/CareLeavers.ContentfulMigration/Migrations/0056-allow-button-in-content.cjs
- src/web/CareLeavers.Web/Contentful/ContentfulEntityResolver.cs
- src/web/CareLeavers.Web/ContentfulRenderers/GDSButtonRenderer.cs
- src/web/CareLeavers.Web/Models/Content/Button.cs
- src/web/CareLeavers.Web/Models/Enums/ButtonType.cs
- src/web/CareLeavers.Web/Program.cs
- src/web/CareLeavers.Web/Views/Shared/Button.cshtml
- src/web/CareLeavers.Web/appsettings.Development.json
Added button to allow users to enter a smaller call to action without having to use the main CTA content type
Fixes: https://dfedigital.atlassian.net/browse/CARE-1046
> Add GDS Button

- src/contentful/CareLeavers.ContentfulMigration/Migrations/0057-add-error-message-to-status-checker.cjs
- src/web/CareLeavers.Web/Controllers/StatusCheckerController.cs
- src/web/CareLeavers.Web/Models/Content/StatusChecker.cs
- src/web/CareLeavers.Web/Views/Shared/StatusChecker.cshtml
Fixes:
- https://dfedigital.atlassian.net/browse/CARE-1048
> Added validation to checker

- docs/operational/Design-System-Changes-Jun-2025.md
- docs/operational/Stopping-The-Site.md
- docs/operational/Subscription-Migration.md
Updated the documentation to detail:
- Upcoming design system changes (govuk rebrand)
- How to stop the site
- Migrating the site
> Documentation Updates

- docs/developers/Development-Process.md
- src/contentful/CareLeavers.ContentfulMigration/Migrations/0060-add-table-to-rich-content.cjs
- src/web/CareLeavers.Web/ContentfulRenderers/GDSTableRenderer.cs
CARE-1333 the root cause was that the headers weren't being searched for properly in the code. And the copy and paste tables in contentful don't automatically add the header section to tables. 
CARE-1326 add the preliminary code to the technical documentation readme section
> CARE-1333 Fixed the table header rendering bug.

- src/e2e/CareLeavers.E2ETests/src/pages/AllSupportPage.ts
> Heading updated - CARE-1304
